parameters:
    app_timezone_default: 'Asia/Yekaterinburg'
    app.admin_email: '%env(ADMIN_EMAIL)%'
    app.admin_password: '%env(ADMIN_PASSWORD)%'
    app.timezone: '%env(default:app_timezone_default:APP_TIMEZONE)%'
    app.payment_webhook_secret: '%env(PAYMENT_WEBHOOK_SECRET)%'
